-- 迁移脚本：给 stores 表增加班次时间字段（可自定义 A/B/C 班次起止时间）
-- 在 Supabase SQL Editor 中执行

ALTER TABLE stores ADD COLUMN IF NOT EXISTS shift_a_start INTEGER NOT NULL DEFAULT 10;
ALTER TABLE stores ADD COLUMN IF NOT EXISTS shift_a_end INTEGER NOT NULL DEFAULT 18;
ALTER TABLE stores ADD COLUMN IF NOT EXISTS shift_b_start INTEGER NOT NULL DEFAULT 12;
ALTER TABLE stores ADD COLUMN IF NOT EXISTS shift_b_end INTEGER NOT NULL DEFAULT 20;
ALTER TABLE stores ADD COLUMN IF NOT EXISTS shift_c_start INTEGER NOT NULL DEFAULT 14;
ALTER TABLE stores ADD COLUMN IF NOT EXISTS shift_c_end INTEGER NOT NULL DEFAULT 22;
