-- 迁移脚本：给 stores 表增加工时/就餐/最低在岗参数
-- 在 Supabase SQL Editor 中执行

ALTER TABLE stores ADD COLUMN IF NOT EXISTS opening_prep_mins INTEGER NOT NULL DEFAULT 60;
ALTER TABLE stores ADD COLUMN IF NOT EXISTS closing_tasks_mins INTEGER NOT NULL DEFAULT 60;
ALTER TABLE stores ADD COLUMN IF NOT EXISTS meal_break_mins INTEGER NOT NULL DEFAULT 30;
ALTER TABLE stores ADD COLUMN IF NOT EXISTS max_meals_per_employee INTEGER NOT NULL DEFAULT 1;
ALTER TABLE stores ADD COLUMN IF NOT EXISTS target_hours_per_employee NUMERIC(4,1) NOT NULL DEFAULT 8.0;
ALTER TABLE stores ADD COLUMN IF NOT EXISTS min_staff_on_duty INTEGER NOT NULL DEFAULT 1;
