-- 迁移脚本：给 stores 表增加出品类型产能字段
-- 在 Supabase SQL Editor 中执行

ALTER TABLE stores ADD COLUMN IF NOT EXISTS productivity_a INTEGER NOT NULL DEFAULT 24;
ALTER TABLE stores ADD COLUMN IF NOT EXISTS productivity_b INTEGER NOT NULL DEFAULT 18;
ALTER TABLE stores ADD COLUMN IF NOT EXISTS productivity_c INTEGER NOT NULL DEFAULT 12;
ALTER TABLE stores ADD COLUMN IF NOT EXISTS productivity_other INTEGER NOT NULL DEFAULT 15;
